# Happy Coding!

service: grabthis

frameworkVersion: "3"

plugins:
  - serverless-frontend-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: "s3:ListBucket"
          Resource: "*"
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::grabthisbucket/*"

functions:
  createBucket:
    handler: upload.createBucket
    events:
      - http:
          path: bucket
          method: post
  listBuckets:
    handler: upload.listBuckets
    events:
      - http:
          path: bucket
          method: get
  deleteBucket:
    handler: upload.deleteBucket
    events:
      - http:
          path: bucket/{bucketName}
          method: delete
  uploadImage:
    handler: upload.uploadImage
    events:
      - http:
          path: image
          method: post
          cors: true # Autoriser les requêtes CORS

resources:
  Resources:
    S3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: grabthisbucket

custom:
  serverless-frontend-plugin:
    distDir: frontend/dist
    build:
      command:
        - npm
        - run
        - build

package:
  patterns:
    - frontend/node_modules/**
